version: '3.8'

services:
  mongo:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tienda
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server_express
      dockerfile: Dockerfile
    container_name: express_server
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      # Usamos el host 'mongo' (nombre del servicio) y credenciales
      MONGO_URI: "mongodb://admin:admin@mongo:27017/tienda?authSource=admin"
      PORT: "5000"
    volumes:
      - ./server_express:/usr/src/app
    command: ["node", "index.js"]

volumes:
  mongo_data:
